"use client";
import { useEffect, useState } from "react";
import type { CompletionEvent } from "@/lib/dojo/practiceEvents/model";
import ExternalResultHistory from "./ExternalResultHistory";
import Link from "./PracticeRouteLink";
export default function PracticeEventHistory({ learningItemId, recent = false, onChanged }: { learningItemId?: string; recent?: boolean; onChanged?:()=>void }) {
  const [refreshVersion,setRefreshVersion]=useState(0);
  function changed(){setRefreshVersion(v=>v+1);onChanged?.();}
  const [events,setEvents]=useState<CompletionEvent[]>([]);const [error,setError]=useState("");const [cursor,setCursor]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);
  async function read(url:string) {const r=await fetch(url,{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error??"完成事件不可用");return j;}
  useEffect(()=>{let live=true;read(`/api/dojo/practice-events${learningItemId?`?learningItemId=${learningItemId}`:""}`).then(j=>{if(live){setEvents(j.events);setCursor(j.cursor);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[learningItemId,refreshVersion]);
  async function retry(id:string){setBusy(true);setError("");try{const r=await fetch("/api/dojo/practice-events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"retry",id})});const j=await r.json();if(!r.ok)throw Error(j.error);setEvents(es=>es.map(e=>e.id===id?j.event:e));onChanged?.();}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function more(){setBusy(true);try{const p=new URLSearchParams({cursor:cursor!});if(learningItemId)p.set("learningItemId",learningItemId);const j=await read(`/api/dojo/practice-events?${p}`);setEvents(es=>[...new Map([...es,...j.events].map(e=>[e.id,e])).values()]);setCursor(j.cursor);}catch(e){setError(String(e));}finally{setBusy(false);}}
  const labels={pending:"待投影",applied:"已套用",needs_retry:"需重試",unlinked:"未連結",unmatched:"單位／規則未匹配"};
  return <section><h3>實際完成事件</h3><p>完成一次活動，不表示能力已學成。</p>{error&&<p role="alert">{error}</p>}{loaded&&<p>已載入有效完成：{events.filter(e=>e.sourceSystem === "context-room" ? e.completionStatus === "completed" : !["withdrawn","unverified"].includes(e.sourceStatus)).length} 次／{events.length} 筆事件（此載入範圍，非全站總數）。</p>}{loaded&&!events.length&&<p>尚無完成事件。舊 activityLog 不自動轉為完成事實。</p>}{(recent?events.slice(0,5):events).map(e=><article className="card" key={e.id}><b>{e.sourceSystem === "context-room" ? "語境修習室" : "日記自譯"}・{e.quantity} {e.unit}</b>{e.sourceSystem === "context-room" ? <><p>來源原日期：{e.practicedOn ?? "來源日期未知"} · 保存／匯入：{e.occurredAt ?? "未知"}</p><p>{e.completionStatus === "completed" ? "有效完成" : e.completionStatus === "withdrawn" ? "已撤回，不列入有效完成" : "證據不足，不列入有效完成"} · {e.sourceAvailability === "deleted" ? "來源已刪除，保留歷史" : e.sourceAvailability === "archived" ? "來源封存" : "來源可用"}</p><p>原日期可能是匯入日；未獨立證明練習時刻。{!e.learningItemIds.length && "尚未連結學科"}</p></> : <p>實際修習 {e.practicedOn} · 原始日記 {e.sourceDate}</p>}<p>光步：{labels[e.projections.output]} · 週盤：{labels[e.bindingStatus ?? e.projections.weekly]}</p><Link href={`/practice/records?record=${e.learningRecordId}`}>查看學習正文</Link>{["pending","needs_retry"].includes(e.projectionStatus)&&<button disabled={busy} onClick={()=>void retry(e.id)}>只重試投影</button>}{e.error&&<p role="alert">{e.error}</p>}</article>)}{cursor&&!recent&&<button disabled={busy} onClick={()=>void more()}>更多完成事件</button>}{!learningItemId&&<ExternalResultHistory recent={recent} onChanged={changed} />}</section>;
}
