import assert from "node:assert/strict";
import { mkdtemp, rm, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { eventService, eventBody, sourceIdentity } from "../lib/dojo/practiceEvents/service";
import { projectWeekly, addOutput, type ProjectedCell } from "../lib/dojo/practiceEvents/projection";
import { preserveProjection } from "../lib/dojo/practiceEvents/compatibility";
import { journalCompletions } from "../lib/dojo/practiceEvents/journal";
import { emptyEnglishJournalPractice, normalizeEnglishJournalPractice } from "../lib/dojo/englishJournal";
import { emptyDailyRecord, emptyWeeklyBoard, normalizeWeeklyBoard, DOJO_TIME_ZONE, taipeiTodayISO } from "../lib/dojo/formal";
import type { LearningEntity } from "../lib/dojo/learningFoundation/model";
import type { CompletionEvent } from "../lib/dojo/practiceEvents/model";
import { withLearningWriteLock } from "../lib/dojo/learningFoundation/fileLock";
import { trackLearningWrite } from "../lib/dojo/learningFoundation/writeOutcome";
import { createPracticeOnce } from "../lib/dojo/learningFoundation/practiceWrite";
async function main() {
 const graph = [{ id: "english", kind: "item", status: "active", legacyKey: "english" }] as LearningEntity[];
 const original = emptyEnglishJournalPractice("2026-09-20", "今天探索新的想法，並用英文留下內容。\n\n【新的觀察】\n這是另一段實際日記內容。");
 original.segments = [original.segments[0], { ...original.segments[0], id: "stable-two", sourceText: "另一個真正有效的段落。" }];
 const candidate = structuredClone(original); candidate.segments[0].draft = "I explored ideas."; candidate.segments[0].finalVersion = "I explored new ideas."; candidate.segments[0].completedAt = "2026-10-01T04:00:00Z";
 const clock = new Date("2026-10-01T04:00:00Z");
 const input = journalCompletions(original, candidate, "page-identity", graph, clock)[0];
 assert.equal(input.practicedOn, taipeiTodayISO(clock)); assert.equal(input.timeZone, DOJO_TIME_ZONE); assert.equal(input.sourceDate, "2026-09-20");
 assert.equal(journalCompletions(original, original, "page", graph, clock).length, 0); // prompt/draft do not complete
 const skipped = structuredClone(candidate); skipped.segments[0].status = "skipped"; assert.equal(journalCompletions(original, skipped, "page", graph, clock).length,0);
 const blank = structuredClone(candidate); blank.segments[0].sourceText=" "; assert.equal(journalCompletions(original, blank, "page", graph, clock).length,0);
 assert.equal(journalCompletions(candidate, candidate, "page", graph, clock).length,0);
 const all = structuredClone(candidate); all.segments[1] = { ...all.segments[1], draft: "new draft", aiRevision: "new final", completedAt: clock.toISOString() }; all.completedAt=clock.toISOString();
 assert.equal(journalCompletions(original, all,"page",graph,clock).length,2); assert.equal(journalCompletions(candidate,all,"page",graph,clock).length,1);
 assert.equal(normalizeEnglishJournalPractice({ ...all, revision: 7 })!.revision, 7);
 const events = new Map<string, CompletionEvent>(); const bodies = new Map(); let creates = 0; let bodyWrites=0; let dailyWrites=0; let weeklyWrites=0;
 let daily = emptyDailyRecord(input.practicedOn); daily.englishRhythm = { touches:["input","vocabulary","transfer"], note:"保留", vocabForgeRounds:4, updatedAt:null }; daily.evening.highlight="真實原內容";
 let board = emptyWeeklyBoard("2026-09-28"); board.cells[0] = { ...board.cells[0], taskInstanceId:"task-stable", text:"英文段落", completion:{ ...board.cells[0].completion, mode:"count",target:3,progress:0,unit:"段" } };
 let failDaily=false, failWeekly=false;
 const service = eventService({ owner:"owner", get:async id=>events.get(id)??null, create:async e=>{ creates++; events.set(e.id,structuredClone(e)); }, update:async e=>{ events.set(e.id,structuredClone(e)); }, body:async e=>{ if(!bodies.has(e.learningRecordId)) {bodyWrites++;bodies.set(e.learningRecordId,eventBody(e));} }, daily:async()=>daily, saveDaily:async(_date,value)=>{ if(failDaily)throw Error("read failed before write"); dailyWrites++;daily=value; }, weekly:async()=>board, saveWeekly:async(_week,value)=>{ if(failWeekly) throw Error("confirmed rejection"); weeklyWrites++;board=value; }, assertKnownOutcome:()=>{} });
 const contextApi = service as unknown as { acceptContext(i: unknown): Promise<CompletionEvent>; updateContext(i: unknown): Promise<CompletionEvent | null> };
 assert.equal(typeof contextApi.acceptContext, "function", "Context Room acceptance must use the existing event repository");
 const contextInput = { sourceId: "00000000-0000-4000-8000-000000000001", sourceRevision: "1", updatedAt: "2026-10-06T01:00:00.000001Z", practicedOn: null, occurredAt: null, timeZone: null, dateSemantics: "stored import date", completionStatus: "completed", sourceAvailability: "available", sourceLocation: "https://lumen-context-room-production-4a2c.up.railway.app/practice-results/00000000-0000-4000-8000-000000000001", activityMode: "topic_speaking", currentContext: { projectId: "p", projectName: "Reading", unitId: "u", unitName: "Chapter 1" }, originalContext: null };
 const contextEvent = await contextApi.acceptContext(contextInput);
 assert.equal(contextEvent.practicedOn, null);
 assert.equal(contextEvent.learningItemIds.length, 0);
 assert.equal(contextEvent.unit, "次");
 assert.equal((await contextApi.acceptContext(contextInput)).id, contextEvent.id);
 const externalWrites = [dailyWrites, weeklyWrites];
 await service.retry(contextEvent.id);
 assert.deepEqual([dailyWrites, weeklyWrites], externalWrites, "external events must not touch output or weekly");
 const storedBody = bodies.get(contextEvent.learningRecordId);
 assert.equal(storedBody.practicedOn, null); assert.equal(storedBody.primaryLearningItemId, null);
 assert.equal(storedBody.originEventId, contextEvent.id);
 const withdrawn = await contextApi.updateContext({ ...contextInput, sourceRevision: "2", updatedAt: "2026-10-07T01:00:00.000001Z", completionStatus: "withdrawn" });
 assert.equal(withdrawn?.id, contextEvent.id); assert.equal(withdrawn?.sourceStatus, "withdrawn");
 const restored = await contextApi.updateContext({ ...contextInput, sourceRevision: "3", updatedAt: "2026-10-08T01:00:00.000001Z" });
 assert.equal(restored?.id, contextEvent.id); assert.equal(restored?.sourceStatus, "available");
 await contextApi.updateContext(contextInput); assert.equal(events.get(contextEvent.id)?.sourceRevision, "3");
 await assert.rejects(contextApi.updateContext({ ...contextInput, sourceRevision: "conflict", updatedAt: "2026-10-08T01:00:00.000001Z" }), /版本/);
 await assert.rejects(contextApi.updateContext({ ...contextInput, sourceRevision: "4", updatedAt: "2026-10-09T01:00:00.000001Z", practicedOn: "2026-10-05" }), /日期/);
 const nextContext = await contextApi.acceptContext({ ...contextInput, sourceId: "00000000-0000-4000-8000-000000000002", sourceLocation: "https://lumen-context-room-production-4a2c.up.railway.app/practice-results/00000000-0000-4000-8000-000000000002" });
 assert.notEqual(nextContext.id, contextEvent.id);
 // Keep original journal count assertions scoped to journals.
 events.clear(); bodies.clear(); creates=0; bodyWrites=0;
 const event = await service.accept(input); assert.equal(creates,1);
 const repeat = await service.accept({ ...input, practicedOn:"2026-10-03", occurredAt:"2026-10-03T04:00:00Z" }); assert.equal(repeat.id,event.id); assert.equal(repeat.practicedOn,input.practicedOn); assert.equal(creates,1);
 failDaily=true; const failed = await service.retry(event.id); assert.equal(failed.projections.output,"needs_retry"); assert.equal(events.size,1); assert.equal(bodyWrites,1);
 failDaily=false; const done = await service.retry(event.id); assert.equal(done.projections.weekly,"unlinked"); assert.equal(done.projectionStatus,"applied"); assert.equal(bodyWrites,1);assert.equal(done.evidence,null);
 assert.deepEqual(daily.englishRhythm.touches,["input","vocabulary","transfer","output"]); assert.equal(daily.englishRhythm.note,"保留");assert.equal(daily.englishRhythm.vocabForgeRounds,4); assert.equal(daily.evening.highlight,"真實原內容");
 const before=[bodyWrites,dailyWrites,weeklyWrites]; await service.retry(event.id); assert.deepEqual([bodyWrites,dailyWrites,weeklyWrites],before);
 const bound = await service.accept({ ...input, sourceId:"different-session",binding:{weekStart:board.weekStart,taskInstanceId:"task-stable"} });
 failWeekly=true; const weeklyFailed=await service.retry(bound.id); assert.equal(weeklyFailed.projections.weekly,"needs_retry"); const dailyBefore=dailyWrites;
 failWeekly=false; await service.retry(bound.id); assert.equal(dailyWrites,dailyBefore);assert.equal(board.cells[0].completion.progress,1);assert.equal((board.cells[0] as ProjectedCell).completionSources!.events.length,1);
 await service.retry(bound.id);assert.equal(board.cells[0].completion.progress,1);
 const secondIncrement=projectWeekly(board,{...bound,id:"distinct-event"});assert.equal(secondIncrement.board!.cells[0].completion.progress,2);assert.equal(projectWeekly(secondIncrement.board!,{...bound,id:"distinct-event"}).board!.cells[0].completion.progress,2);
 const moved = structuredClone(board); moved.cells[4]={ ...moved.cells[0],index:4 }; moved.cells[0]={ ...emptyWeeklyBoard(board.weekStart).cells[0] };assert.equal(projectWeekly(moved,bound).board!.cells[4].completion.progress,1);
 const removed = structuredClone(board);removed.cells[0].taskInstanceId=null;assert.equal(projectWeekly(removed,bound).state,"unlinked");
 const ambiguous=structuredClone(board);ambiguous.cells[1]={ ...ambiguous.cells[0],index:1 };assert.equal(projectWeekly(ambiguous,bound).state,"unlinked");
 const mismatch=structuredClone(board);mismatch.cells[0].completion.unit="篇";assert.equal(projectWeekly(mismatch,bound).state,"unmatched");
 const archived=structuredClone(board);archived.archivedAt=clock.toISOString();assert.equal(projectWeekly(archived,bound).state,"unlinked");
 const manual=emptyWeeklyBoard(board.weekStart);manual.cells[0]={ ...board.cells[0],completionSources:undefined,completion:{ ...board.cells[0].completion, progress:3 },completed:true } as ProjectedCell;
 assert.equal(projectWeekly(manual,bound).board!.cells[0].completion.progress,3);
 const single=structuredClone(manual);single.cells[0].completion.mode="single";single.cells[0].completion.progress=0;assert.equal(projectWeekly(single,bound).board!.cells[0].completion.progress,3);
 const stale=normalizeWeeklyBoard(board,board.weekStart);delete stale.cells[0].completionSources;stale.cells[0].completion.progress=0;
 const retained=preserveProjection("行光週盤-20260928",stale,board) as typeof board;assert.equal(retained.cells[0].completion.progress,1);assert.equal((retained.cells[0] as ProjectedCell).completionSources!.events.length,1);
 assert.equal(normalizeWeeklyBoard(board,board.weekStart).cells[0].completionSources!.events.length,1);
 const oldDaily=emptyDailyRecord(input.practicedOn);const protectedDaily=preserveProjection("行光今日-20261001",oldDaily,{ ...daily,practiceEventOutput:true }) as typeof daily;assert.ok(protectedDaily.englishRhythm.touches.includes("output"));
 assert.equal(addOutput(addOutput(daily,event),bound).englishRhythm.touches.filter(t=>t==="output").length,1);
 const boundary=new Date("2026-10-01T00:00:00Z");assert.equal(journalCompletions(original,candidate,"page",graph,boundary)[0].practicedOn,taipeiTodayISO(boundary));
 const directory=await mkdtemp(join(tmpdir(),"r2-3-events-"));
 try {
  let entered!:()=>void;let release!:()=>void;const enteredPromise=new Promise<void>(r=>entered=r),releasePromise=new Promise<void>(r=>release=r);
  const first=withLearningWriteLock(async()=>{entered();await releasePromise;return service.accept({ ...input,sourceId:"concurrent" });},directory);await enteredPromise;
  await assert.rejects(withLearningWriteLock(()=>service.accept({ ...input,sourceId:"concurrent" }),directory),/另一筆/);release();await first;
  const beforeCreates=creates;await withLearningWriteLock(()=>service.accept({ ...input,sourceId:"concurrent" }),directory);assert.equal(creates,beforeCreates);
  await assert.rejects(withLearningWriteLock(async()=>{throw Error("read failure");},directory),/讀取/);await assert.rejects(access(join(directory,"learning-writer.lock")));await withLearningWriteLock(async()=>true,directory);
  const identity=sourceIdentity("owner","dojo","unknown","session");let dispatched=0;
  await assert.rejects(withLearningWriteLock(()=>createPracticeOnce(identity,()=>trackLearningWrite(async()=>{dispatched++;throw Error("response lost after commit");}),directory),directory),/結果未確認/);
  await access(join(directory,"learning-writer.lock"));await access(join(directory,`practice-${identity}.intent`));
  await assert.rejects(withLearningWriteLock(async()=>{dispatched++;},directory),/另一筆/);assert.equal(dispatched,1);
 } finally { await rm(directory,{recursive:true,force:true}); }
 console.log("PASS practice events: transition rules, source dedup, retry date/timezone, event-first failures, daily preservation, stable weekly binding/count/unit/manual provenance, projection no-op, concurrent lock, unknown response fail-closed intent");
}
main().catch(e=>{ console.error(e);process.exitCode=1; });
